### ISSUE TITLE
Create github webpage for Sparkiy

### ISSUE THREAD

**Issue by AleksandarDev** [Sparkiy/sparkiy#4]
Something similar to http://spark.github.io/

**Comment by BiohazardFox** [comment]
I can do the Webpage.

**Comment by AleksandarDev** [comment]
- [x] Center content
- [x] Remove Windows Store reference
- [x] Add Sparkiy Projects
- [x] Add Sparkiy CMS
- [x] Add group `Components`
  - [x] Sparkiy Editor
  - [x] Sparkiy Canvas
- [ ] Create list of tools (Visual Studio, ZenHub, etc.)

**Comment by AleksandarDev** [comment]
We moved website to [collaborate.sparkiy.com](http://collaborate.sparkiy.com). It is also available through [sparkiy.github.io/sparkiy](http://sparkiy.github.io/sparkiy)

We are no longer using `BetterCMS`. `nanoc` is used for both reference and collaborate pages for static generation. 

Take a look at [Using nanoc](https://github.com/Sparkiy/sparkiy-reference/wiki/Using-nanoc) for more info.
